apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
  namespace: yepez-sagnay-parra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z tickets-db 5432; do echo "esperando tickets-db..."; sleep 2; done
              until nc -z rabbitmq 5672; do echo "esperando rabbitmq..."; sleep 2; done
      containers:
        - name: tickets
          image: yepez-sagnay-parra-tickets:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: tickets-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USUARIO
              valueFrom: { secretKeyRef: { name: parras-secrets, key: DB_USER } }
            - name: DB_CONTRASENA
              valueFrom: { secretKeyRef: { name: parras-secrets, key: DB_PASSWORD } }
            - name: DB_NOMBRE
              valueFrom: { configMapKeyRef: { name: parras-config, key: DB_NAME_TICKETS } }
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: parras-secrets, key: JWT_SECRET } }
            - name: RABBITMQ_HOST
              valueFrom: { configMapKeyRef: { name: parras-config, key: RABBITMQ_HOST } }
            - name: RABBITMQ_PORT
              valueFrom: { configMapKeyRef: { name: parras-config, key: RABBITMQ_PORT } }
            - name: RABBITMQ_USER
              valueFrom: { secretKeyRef: { name: parras-secrets, key: RABBITMQ_USER } }
            - name: RABBITMQ_PASSWORD
              valueFrom: { secretKeyRef: { name: parras-secrets, key: RABBITMQ_PASSWORD } }
            - name: RABBITMQ_EXCHANGE
              valueFrom: { configMapKeyRef: { name: parras-config, key: RABBITMQ_EXCHANGE } }
            - name: RABBITMQ_ROUTING_KEY
              valueFrom: { configMapKeyRef: { name: parras-config, key: RABBITMQ_ROUTING_KEY } }
            - name: ZONES_SERVICE_URL
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONES_SERVICE_URL } }
            - name: VEHICLES_SERVICE_URL
              valueFrom: { configMapKeyRef: { name: parras-config, key: VEHICLES_SERVICE_URL } }
            - name: ASSIGNMENTS_SERVICE_URL
              valueFrom: { configMapKeyRef: { name: parras-config, key: ASSIGNMENTS_SERVICE_URL } }
            - name: TICKET_PRICE
              valueFrom: { configMapKeyRef: { name: parras-config, key: TICKET_PRICE } }
            - name: PLACE_RATE_CAR
              valueFrom: { configMapKeyRef: { name: parras-config, key: PLACE_RATE_CAR } }
            - name: PLACE_RATE_BIKE
              valueFrom: { configMapKeyRef: { name: parras-config, key: PLACE_RATE_BIKE } }
            - name: PLACE_RATE_BUS
              valueFrom: { configMapKeyRef: { name: parras-config, key: PLACE_RATE_BUS } }
            - name: ZONE_MULT_REGULAR
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONE_MULT_REGULAR } }
            - name: ZONE_MULT_VIP
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONE_MULT_VIP } }
            - name: ZONE_MULT_INTERNAL
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONE_MULT_INTERNAL } }
            - name: ZONE_MULT_EXTERNAL
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONE_MULT_EXTERNAL } }
            - name: ZONE_MULT_PREFERENTIAL
              valueFrom: { configMapKeyRef: { name: parras-config, key: ZONE_MULT_PREFERENTIAL } }
---
apiVersion: v1
kind: Service
metadata:
  name: tickets
  namespace: yepez-sagnay-parra
spec:
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
